services:

  # Serviço para o banco de dados MySQL
  main-db:
    image: mysql
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Senha do root
    ports:
      - '8000:8000'  # Mapeia a porta 3306 para o host
    
    expose:
      - '8000'

    volumes:
      - ./data/db:/var/lib/mysql  # Persistir dados do banco
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:8.0
    build:
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
